version: '3.9'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    networks:
      - app-network
    volumes:
      - db/data:/var/lib/postgresql/data
      - db/logs:/var/log/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: application
    volumes:
      - ./src:/src
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
